sudo: required

services:
  - docker

before_install:
  - travis_wait 30 docker build -t julienchastang/emacs:latest .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push julienchastang/emacs:latest
